title: Steven Waterman
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog!
#permalink: 'http://www.stevenwaterman.uk'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.stevenwaterman.uk" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Steven Waterman # add your name
author-img: steven-waterman.jpg # add your photo
about-author: Founder of <a href="https://lexoral.com">Lexoral</a><br><br>Watch me violently oscillate between hacky bodges and the pursuit of perfectionism. # add description
social-twitter: SteWaterman
#social-facebook: # add your Facebook handle
social-github: stevenwaterman # add your Github handle
social-linkedin: steven-waterman # add your Linkedin handle
social-email: website@stevenwaterman.uk # add your Email address
cv: cv.pdf

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
# remote_theme: flexible-jekyll
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
